/**
 * Liste aller im Handwerk anerkannten Ausbildungsberufe (Gewerke).
 * Reihenfolge wie vom Nutzer vorgegeben (alphabetisch nach DIN-ähnlicher Sortierung).
 */
export const GEWERKE: string[] = [
  "Änderungsschneider/-in",
  "Anlagenmechaniker/-in für Sanitär-, Heizungs- und Klimatechnik",
  "Augenoptiker/-in",
  "Ausbaufacharbeiter/-in",
  "Automobilkaufmann/-frau",
  "Bäcker/-in",
  "Baugeräteführer/-in",
  "Bauwerksabdichter/-in",
  "Bauzeichner/-in",
  "Behälter- und Apparatebauer/-in",
  "Bestattungsfachkraft",
  "Beton- und Stahlbetonbauer/-in",
  "Bodenleger/-in",
  "Bogenmacher/-in",
  "Bootsbauer/-in",
  "Brauer/-in und Mälzer/-in",
  "Brunnenbauer/-in",
  "Buchbinder/-in",
  "Böttcher/-in",
  "Büchsenmacher/-in",
  "Bürsten- und Pinselmacher/-in",
  "Chirurgiemechaniker/-in",
  "Dachdecker/-in",
  "Drechsler/-in",
  "Edelsteinschleifer/-in",
  "Elektroniker/-in",
  "Elektroniker/-in für Gebäudesystemintegration",
  "Elektroniker/-in für Maschinen und Antriebstechnik",
  "Estrichleger/-in",
  "Fachkraft für Holz- und Bautenschutzarbeiten",
  "Fachkraft für Lederherstellung und Gerbereitechnik",
  "Fachkraft für Metalltechnik",
  "Fachverkäufer/-in im Lebensmittelhandwerk",
  "Fahrradmonteur/-in",
  "Fahrzeuglackierer/-in",
  "Feinoptiker/-in",
  "Feinwerkmechaniker/-in",
  "Feuerungs- und Schornsteinbauer/-in",
  "Flechtwerkgestalter/-in",
  "Fleischer/-in",
  "Fliesen-, Platten- und Mosaikleger/-in",
  "Fotograf/-in",
  "Fotomedienfachmann/-frau",
  "Friseur/-in",
  "Gebäudereiniger/-in",
  "Geigenbauer/-in",
  "Gerüstbauer/-in",
  "Glas- und Porzellanmaler/-in",
  "Glasapparatebauer/-in",
  "Glasbläser/-in",
  "Glaser/-in",
  "Glasveredler/-in",
  "Gold- und Silberschmied/-in",
  "Graveur/-in",
  "Handzuginstrumentenmacher/-in",
  "Hochbaufacharbeiter/-in",
  "Holz- und Bautenschützer/-in",
  "Holzbildhauer/-in",
  "Holzblasinstrumentenmacher/-in",
  "Holzspielzeugmacher/-in",
  "Hörakustiker/-in",
  "Informationselektroniker/-in",
  "Kanalbauer/-in",
  "Karosserie- und Fahrzeugbaumechaniker/-in",
  "Kaufmann/-frau für Büromanagement",
  "Keramiker/-in",
  "Kerzenhersteller/-in und Wachsbildner/-in",
  "Klavier- und Cembalobauer/-in",
  "Klempner/-in",
  "Konditor/-in",
  "Konstruktionsmechaniker/-in",
  "Kosmetiker/-in",
  "Kraftfahrzeugmechatroniker/-in",
  "Kürschner/-in",
  "Land- und Baumaschinenmechatroniker/-in",
  "Maler/-in und Lackierer/-in",
  "Maskenbildner/-in",
  "Maurer/-in",
  "Maßschneider/-in",
  "Maßschuhmacher/-in",
  "Mechaniker/-in für Reifen- und Vulkanisationstechnik",
  "Mechatroniker/-in",
  "Mechatroniker/-in für Kältetechnik",
  "Mediengestalter/-in Digital und Print",
  "Medientechnologe/-in Druck",
  "Medientechnologe/-in Siebdruck",
  "Metall- und Glockengießer/-in",
  "Metallbauer/-in",
  "Metallbildner/-in",
  "Metallblasinstrumentenmacher/-in",
  "Modist/-in",
  "Naturwerksteinmechaniker/-in",
  "Oberflächenbeschichter/-in",
  "Ofen- und Luftheizungsbauer/-in",
  "Orgelbauer/-in",
  "Orthopädieschuhmacher/-in",
  "Orthopädietechnik-Mechaniker/-in",
  "Parkettleger/-in",
  "Rollladen- und Sonnenschutzmechatroniker/-in",
  "Sattler/-in",
  "Schilder- und Lichtreklamehersteller/-in",
  "Schuhmacher/-in",
  "Seiler/-in",
  "Steinmetz/-in und Steinbildhauer/-in",
  "Straßenbauer/-in",
  "Stuckateur/-in",
  "Tischler/-in",
  "Technischer Modellbauer/-in",
  "Textilreiniger/-in",
  "Tiefbaufacharbeiter/-in",
  "Vergolder/-in",
  "Wärme-, Kälte- und Schallschutzisolierer/-in",
  "Zahntechniker/-in",
  "Zimmerer/Zimmerin",
  "Zweiradmechatroniker/-in",
];

/**
 * Liefert den "Stamm" eines Gewerks, also alles vor dem ersten Schrägstrich
 * mit Geschlechts-Suffix (z. B. "Tischler/-in" → "Tischler", "Maler/-in und
 * Lackierer/-in" → "Maler"). Wird für tolerantes Filter-Matching verwendet,
 * damit alte Einträge wie "Tischler/in" auch gefunden werden.
 */
export function gewerkStamm(value: string): string {
  if (!value) return "";
  const beforeSlash = value.split("/")[0];
  return beforeSlash.trim().toLowerCase();
}
